In [1]:
import tesnorflow as tf

ModuleNotFoundError: No module named 'tesnorflow'

In [2]:
pip install tensorflow

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

  Using cached tensorflow-2.16.2-cp311-cp311-win_amd64.whl.metadata (3.3 kB)
  Using cached tensorflow_intel-2.16.2-cp311-cp311-win_amd64.whl.metadata (5.0 kB)
  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
  Using cached gast-0.6.0.tar.gz (27 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached h5py-3.11.0-cp311-cp311-win_amd64.whl.metadata (2.5 kB)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached ml_dtypes-0.3.2-cp311-cp311-win_amd64.whl.metadata (20 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\rajesh\\AppData\\Roaming\\Python\\Python311\\site-packages\\tensorflow\\python\\_pywrap_tensorflow_internal.pyd'
Check the permissions.



In [3]:
pip install tensorflow -U

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [17]:
import tensorflow as tf
import numpy as np

In [18]:
tf

<module 'tensorflow' from 'C:\\Users\\rajesh\\AppData\\Roaming\\Python\\Python311\\site-packages\\tensorflow\\__init__.py'>

In [19]:
# create tensors
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])

print("Tensor a:", a)
print("Tensor b:", b)

Tensor a: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Tensor b: tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [20]:
a[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [24]:
# create tensors
x = tf.constant([[1,2,3],[7,8,9]], dtype=np.int8)
y = tf.constant([[4,5], [6,2]])

print("Tensor a:", x)
print("Tensor b:", y)

Tensor a: tf.Tensor(
[[1 2 3]
 [7 8 9]], shape=(2, 3), dtype=int8)
Tensor b: tf.Tensor(
[[4 5]
 [6 2]], shape=(2, 2), dtype=int32)


In [25]:
# Multiply tensors
e = tf.multiply(a,b)
print("Multiplication:", e)

Multiplication: tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [26]:
a * b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 10, 18])>

In [27]:
# Divide tensors
f = tf.divide(a, b)
print("Division:", f)

Division: tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [28]:
a/b

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.4 , 0.5 ])>

In [29]:
a//b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0])>

In [30]:
b//a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 2])>

In [31]:
b/a

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4. , 2.5, 2. ])>

In [34]:
# Matrix multiplication
a_matrix = tf.constant([[1,2], [3,4]])
b_matrix = tf.constant([[5,6], [7,8]])

g = tf.matmul(a_matrix, b_matrix)
print("Matrix Multiplication:", g)

Matrix Multiplication: tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
